import Stream.cons

/**
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */

object Problem_02 {

  def sumFibBelow(max:Int):Int = 0

  def sumFibBelow(max:Int, stream:Iterable[Int]):Int = 0

  val fibs:Stream[Int] = Stream.empty
}
